version: '3'

services:

  app:
    image: cloudguardian:0.0.2
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:3001"
    # env_file: .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_PORT: 5432
      DB_USERNAME: alex
      DB_PASSWORD: alex
      DB_DATABASE: newdatabase
      DB_HOST: db
    depends_on:
      - db
      - redis


  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: alex
      POSTGRES_DB: newdatabase
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

